source 'https://rubygems.org'

gem 'bcrypt'
gem 'sinatra-activerecord'

gem 'debase', '0.2.5.beta2', require: false
gem 'rspec', require: false
gem 'rubocop', require: false
gem 'rubocop-md', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
gem 'ruby-debug-ide', require: false
gem 'webrick', require: false
